version: "3.6"

services:
  database:
    image: postgres:12
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=order-bot-dev
      - POSTGRES_PASSWORD=postgres

  cache:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes: 
      - redis:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Singapore

  api:
    image: order-bot:latest
    ports:
      - 4000:4000
    volumes:
      - ./:/app
    links:
      - database
      - cache
    environment:
      - PORT=4000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=order-bot-dev
      - REDIS_URL=redis://cache:6379/0

volumes:
  psql: {}
  redis: {}
