version: "3.6"

services:
  database:
    image: postgres:12
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=order-bot-dev
      - POSTGRES_PASSWORD=postgres
  api:
    image: order-bot:latest
    ports:
      - 4000:4000
    volumes:
      - ./:/app
    links:
      - database
    environment:
      - PORT=4000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=order-bot-dev
volumes:
  psql: {}
