// Code generated by sqlc. DO NOT EDIT.
// source: orders.sql

package models

import (
	"context"
	"time"
)

const cancelOrder = `-- name: CancelOrder :exec
UPDATE orders
SET active = FALSE
WHERE chat_id = $1
AND active = TRUE
`

func (q *Queries) CancelOrder(ctx context.Context, chatID int32) error {
	_, err := q.exec(ctx, q.cancelOrderStmt, cancelOrder, chatID)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (chat_id, title, expiry)
VALUES ($1, $2, $3)
RETURNING id, chat_id, title, expiry, active
`

type CreateOrderParams struct {
	ChatID int32     `json:"chat_id"`
	Title  string    `json:"title"`
	Expiry time.Time `json:"expiry"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.queryRow(ctx, q.createOrderStmt, createOrder, arg.ChatID, arg.Title, arg.Expiry)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Title,
		&i.Expiry,
		&i.Active,
	)
	return i, err
}

const getActiveOrder = `-- name: GetActiveOrder :one
SELECT id, chat_id, title, expiry, active FROM orders
WHERE chat_id = $1
AND expiry > $2
AND active = TRUE
`

type GetActiveOrderParams struct {
	ChatID int32     `json:"chat_id"`
	Expiry time.Time `json:"expiry"`
}

func (q *Queries) GetActiveOrder(ctx context.Context, arg GetActiveOrderParams) (Order, error) {
	row := q.queryRow(ctx, q.getActiveOrderStmt, getActiveOrder, arg.ChatID, arg.Expiry)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Title,
		&i.Expiry,
		&i.Active,
	)
	return i, err
}
