// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"context"
)

type Querier interface {
	CancelOrder(ctx context.Context, chatID int32) (Order, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	DeactivateOrder(ctx context.Context, id int32) error
	DeleteItemByUser(ctx context.Context, arg DeleteItemByUserParams) (Item, error)
	GetActiveOrder(ctx context.Context, chatID int32) (Order, error)
	GetItem(ctx context.Context, arg GetItemParams) (Item, error)
	GetItemsByOrderID(ctx context.Context, orderID int32) ([]Item, error)
	GetOrderByID(ctx context.Context, id int32) (Order, error)
	GetUserItems(ctx context.Context, arg GetUserItemsParams) ([]Item, error)
	UpdateExpiry(ctx context.Context, arg UpdateExpiryParams) error
	UpdateItemQuantity(ctx context.Context, arg UpdateItemQuantityParams) (Item, error)
	UpdateReminder(ctx context.Context, arg UpdateReminderParams) error
}

var _ Querier = (*Queries)(nil)
